### ISSUE TITLE
look like the installation file have some problem

### ISSUE THREAD

**Issue by sngmn451** [diecodev/moick#30]
Hi look like the `pnpm install @moick/qwik` have some problem.

The node_modules folder comes as per image below.
![image](https://github.com/diecodev/moick/assets/2971450/c984b898-5aee-4d96-8951-015983d955f1)

My set up:
- m1 mac mini
- os: 13.5.2

**Comment by iamriajul** [comment]
I've temporary fixed package for this: https://www.npmjs.com/package/moick-qwik-fixed

**Comment by diecodev** [comment]
@iamriajul if you are agree, can u pls make a pr to update the pkg?

**Comment by iamriajul** [comment]
I think the problem is not related to code but to deployment.
I just changed the index.ts to like this:
```ts
export { Toaster, toast } from "./components";
export * from "./types";
```
And run commands like this to deploy to npm:
- `cd packages/qwik`
- `pnpm run build`
- `pnpm publish`

**Comment by iamriajul** [comment]
![image](https://github.com/diecodev/moick/assets/24244379/f6ef661e-b7a9-48b1-bba6-78cda672d74f)
I think when you deployed you have forgot to run `pnpm run build` before `pnpm publish`

**Comment by diecodev** [comment]
@iamriajul Sorry for the late reply. I have been busy all year with work and university. I have been working on the library to make it as similar as possible to [sonner](https://sonner.emilkowal.ski/) (react library) but I have encountered some framework issues that I have already reported in the github repo. As soon as I get an answer from the qwik core team there will be many changes to the library to support **ALL METHODS** that sonner uses. Merry christmas and happy coding!

**Comment by diecodev** [comment]
@sngmn451 @iamriajul We are pleased to inform you that this component library will be deprecated to make way for [qwik-sonner](https://github.com/diecodev/qwik-sonner). In this new library you will be able to have all the benefits of [sonner](https://sonner.emilkowal.ski/) but in a native way with [qwik](https://qwik.builder.io/). Sorry for replying so late, as I said before, I've been busy with work and university. Greetings and happy coding!
